#!/usr/bin/env python3
"""Build the concise, self-contained Paper 0 presentation readout."""

from __future__ import annotations

import base64
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "paper0/reports/paper0-presentation-readout-2026-08-28.html"
FIGURES = {
    "fields": ROOT / "paper0/figures/post_ecrd_old_85604_bounded_rollout/bounded-rollout-example-fields.png",
    "transport": ROOT / "paper0/figures/post_ecrd_old_85604_bounded_rollout/bounded-rollout-transport-traces.png",
    "covariance": ROOT / "paper0/figures/phase3_b5_covariance_localization/b5-covariance-separatrix-transport.png",
    "spatial": ROOT / "paper0/figures/physics_first_spatial_s0_2026_08_28/s0_spatial_reconstruction_hero.png",
    "scale": ROOT / "paper0/figures/physics_first_spatial_s0_2026_08_28/s0_spatial_skill_by_scale.png",
}
SUMMARY = ROOT / "paper0/results/physics_first_spatial_s0_2026_08_28/job_6958207_summary.json"


def uri(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(path)
    return "data:image/png;base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def main() -> None:
    summary = json.loads(SUMMARY.read_text(encoding="utf-8"))
    heldout = summary["heldout_diagnostic_c"]
    band = summary["retained_power_ratio_n20_to_n35"]
    high = summary["retained_power_ratio_n_ge_40"]
    images = {name: uri(path) for name, path in FIGURES.items()}
    html = f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Paper 0 · Current physics readout</title><style>
:root{{--ink:#17232d;--muted:#5f6b74;--rule:#dde4e7;--teal:#147d80;--soft:#edf6f5;--paper:#fff;--bg:#eef2f3;--sans:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif;--serif:"Iowan Old Style",Georgia,serif}}*{{box-sizing:border-box}}body{{margin:0;background:var(--bg);color:var(--ink);font:18px/1.55 var(--serif)}}.page{{max-width:76rem;margin:auto;background:var(--paper);padding:3.5rem 3rem 5rem;box-shadow:0 0 35px #2233}}h1{{font:700 3.15rem/1.04 var(--sans);letter-spacing:-.04em;max-width:65rem;margin:.5rem 0 1rem}}h2{{font:700 1.8rem/1.15 var(--sans);letter-spacing:-.02em;margin:.3rem 0 .8rem}}.eyebrow,.label{{font:750 .73rem var(--sans);letter-spacing:.12em;text-transform:uppercase;color:var(--teal)}}.dek,.lead{{color:var(--muted);max-width:60rem}}.meta{{font:.78rem var(--sans);color:var(--muted);display:flex;gap:1.2rem;flex-wrap:wrap;margin-top:1rem}}section{{padding:2.6rem 0;border-top:1px solid var(--rule)}}.answer{{background:var(--soft);border-left:4px solid var(--teal);padding:1rem 1.25rem;margin:1.3rem 0}}.answer p{{margin:.35rem 0}}.cards{{display:grid;grid-template-columns:repeat(3,1fr);gap:.8rem}}.card{{background:#fafbfb;border-top:3px solid var(--teal);padding:.9rem}}.card strong{{display:block;font:700 1.35rem var(--sans);color:var(--teal)}}.card span{{font:.82rem/1.35 var(--sans);color:var(--muted)}}figure{{margin:1.6rem 0 0;border:1px solid var(--rule);border-radius:8px;overflow:hidden}}figure img{{display:block;width:100%;height:auto}}figcaption{{border-top:1px solid var(--rule);padding:.9rem 1.1rem;font:.82rem/1.5 var(--sans);color:var(--muted)}}.num{{font-weight:750;color:var(--teal)}}table{{width:100%;border-collapse:collapse;font:.84rem/1.45 var(--sans)}}th,td{{padding:.7rem .6rem;border-bottom:1px solid var(--rule);text-align:left;vertical-align:top}}th{{color:var(--muted);text-transform:uppercase;font-size:.72rem;letter-spacing:.06em}}footer{{font:.75rem/1.5 var(--sans);color:var(--muted);padding-top:2rem}}@media(max-width:800px){{.page{{padding:2rem 1rem}}h1{{font-size:2.3rem}}.cards{{grid-template-columns:1fr}}}}
</style></head><body><div class="page"><header><p class="eyebrow">Paper 0 · presentation readout · 28 August 2026</p><h1>What the emulator learns—and what still blocks diagnostic assimilation</h1><p class="dek">A short, physics-first summary of completed 85604 evidence. No 85606 result appears here.</p><div class="meta"><span>old 85604 only</span><span>five reduced fields</span><span>transport evaluated from fields, not used as a loss</span></div></header>
<section><p class="label">Short answer</p><h2>Mean dynamics improved. Joint transport uncertainty did not.</h2><div class="answer"><p><strong>Forecast:</strong> repeated short steps retain turbulent structure and transport timing better than large direct jumps.</p><p><strong>Uncertainty:</strong> the ensemble gets local transport spread roughly right, but distant patches cancel too strongly. Total transport spread is only about half of what the errors require.</p><p><strong>Sparse measurements:</strong> two local density views contain real information about a separate unseen region, mainly at low and middle toroidal modes.</p></div><div class="cards"><div class="card"><strong>0.41–0.49</strong><span>integrated transport spread divided by observed error; ideal is 1</span></div><div class="card"><strong>{heldout['pearson_correlation']:.3f}</strong><span>correlation when two density views predict a third unseen view</span></div><div class="card"><strong>{100*heldout['relative_mse_skill_vs_zero']:.1f}%</strong><span>lower unseen-view error than predicting no fluctuation</span></div></div></section>
<section><p class="label">01 · Forecasted structure</p><h2>Small rollout steps retain structure; long jumps smooth it away</h2><p class="lead">At the same 25.055-microsecond horizon, eight one-frame steps keep much more of the pressure and potential pattern than two four-frame steps or one direct jump.</p><figure><img alt="Truth and three deterministic rollout schedules for pressure and potential" src="{images['fields']}"><figcaption><span class="num">Figure 1.</span> Same truth and horizon, different rollout schedules. This is a representative preregistered example, not a claim based on appearance alone.</figcaption></figure></section>
<section><p class="label">02 · Mean transport</p><h2>The short-step rollout follows transport timing best</h2><p class="lead">Each point below is a separate rolling-origin forecast. The one-frame rollout tracks many rises and falls; the longer direct forecasts collapse toward a smooth, low-amplitude trace.</p><figure><img alt="Particle and total energy transport across rolling-origin validation forecasts" src="{images['transport']}"><figcaption><span class="num">Figure 2.</span> Black is truth. Blue is repeated one-frame prediction. Pink and orange are longer jumps. This supports the mean-dynamics model, but it does not establish calibrated uncertainty.</figcaption></figure></section>
<section><p class="label">03 · Why the ensemble still fails</p><h2>Correct local spread does not imply correct total transport spread</h2><p class="lead">Spread-skill ratio compares forecast spread with actual error; 1 is ideal. Local values are near 1. Integrated values are 0.41–0.49 because distant fluctuations cancel incorrectly. Simply inflating every member enough to fix the total would make local uncertainty more than twice too large.</p><figure><img alt="Local and integrated transport spread-skill ratios" src="{images['covariance']}"><figcaption><span class="num">Figure 3.</span> The joint residual-diffusion ensemble captures local amplitude better than domain-scale coordination. This is the main reason assimilation and diagnostic ranking remain provisional.</figcaption></figure></section>
<section><p class="label">04 · Model ladder</p><h2>Each model tested one specific explanation</h2><table><thead><tr><th>Model</th><th>Assumption tested</th><th>What happened</th></tr></thead><tbody>
<tr><td><strong>Compressed latent diffusion</strong></td><td>A small latent state retains the physics needed for future frames.</td><td>It produced plausible fields, but rollout structure and transport decayed. A larger latent recovered fine reconstruction detail without repairing dynamics or assimilation.</td></tr>
<tr><td><strong>Codec-free deterministic operator</strong></td><td>The visible five-field transition is mostly predictable, and compression is the bottleneck.</td><td>Direct field prediction improved short-horizon structure and mean transport. Repeated short steps beat large jumps physically. It cannot represent forecast uncertainty.</td></tr>
<tr><td><strong>Joint residual diffusion</strong></td><td>Unpredictable error can be learned as one joint distribution around the deterministic mean.</td><td>It improved local spread and spectra. It missed how distant transport patches fluctuate together, so integrated spread stayed near 0.4–0.5 of the required value.</td></tr>
<tr><td><strong>Deep state-conditioned diffusion</strong></td><td>The residual distribution changes with the current plasma state.</td><td>Conditioning improved marginal scores and was the strongest earlier stochastic baseline, but it still did not recover domain-scale transport covariance.</td></tr>
<tr><td><strong>Toroidally equivariant, multiscale diffusion</strong></td><td>Translation symmetry and noise at several spatial scales are the missing ingredients.</td><td>Symmetry became cleaner, but more structure did not monotonically improve transport. Noise at several resolutions was not the same as one coherent global plasma state.</td></tr>
<tr><td><strong>Persistent global–local generator</strong></td><td>A latent state shared across space and four future frames can coordinate the ensemble.</td><td>Its mean forecast improved spectra, density–potential phase, and mean transport. Its stochastic branch remained too weak: integrated spread-skill fell to about 0.22.</td></tr>
<tr><td><strong>Full evolved-state operator pilot</strong></td><td>Missing Hermes variables, rather than stochastic modeling, are the main bottleneck.</td><td>The pilot overfit: training improved while chronological validation stayed near the zero-increment baseline. This hypothesis remains plausible but unproven.</td></tr>
</tbody></table></section>
<section><p class="label">05 · Sparse simultaneous measurements</p><h2>Two local density views predict part of an unseen region</h2><p class="lead">This is spatial reconstruction, not forecasting. Measurements A and B are revealed at one instant; region C is hidden and predicted.</p><figure><img alt="Hidden truth sparse measurements reconstruction and unseen-region prediction" src="{images['spatial']}"><figcaption><span class="num">Figure 4.</span> A simple linear reconstruction, fit chronologically on training frames only. The shown frame has median unseen-region error. The boxes are BES/GPI-like averages, not complete experimental forward models.</figcaption></figure><figure><img alt="Spatial reconstruction skill by distance toroidal mode and plasma region" src="{images['scale']}"><figcaption><span class="num">Figure 5.</span> Recovered power at physical n=20–35 is {', '.join(f'{k} {100*v:.0f}%' for k,v in band.items())}. At n≥40 it falls to {', '.join(f'{k} {100*v:.0f}%' for k,v in high.items())}. Sparse views recover coherent structure, not all fine turbulence.</figcaption></figure></section>
<section><p class="label">Bottom line</p><h2>What is safe to present</h2><table><thead><tr><th>Supported</th><th>Not supported yet</th></tr></thead><tbody><tr><td>Short-step deterministic rollouts preserve structure and mean transport better than long direct jumps.</td><td>No current ensemble has passed the integrated transport-covariance gate.</td></tr><tr><td>The uncertainty failure is spatial coordination, not simply too little scalar noise.</td><td>Earlier ETKF diagnostic rankings are exploratory until the prior covariance improves.</td></tr><tr><td>Two sparse simultaneous density measurements recover useful nonlocal low/mid-mode information.</td><td>The synthetic boxes are not full experimental diagnostic models, and this is not cross-shot validation.</td></tr></tbody></table></section>
<footer>Self-contained local HTML. All figures are embedded. Source: completed old-85604 Paper 0 artifacts only. The current matched four-model extraction is intentionally omitted until its final replay check completes.</footer></div></body></html>'''
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(html, encoding="utf-8")
    print(json.dumps({"status": "ok", "output": str(OUTPUT), "bytes": OUTPUT.stat().st_size}))


if __name__ == "__main__":
    main()
